# Generated by Django 4.0.6 on 2022-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
