# Generated by Django 4.0.6 on 2022-07-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_user_image_user_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
