# Generated by Django 4.0.6 on 2022-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
